# Default / fallback config (used if no profile active)
spring:
  profiles:
    active: dev   # Default to dev locally

  jpa:
    hibernate:
      ddl-auto: none   # Flyway will handle schema → disable Hibernate auto-DDL
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true